'use strict';

/**
 * Module 15 Step 6 — decideTrust regression gate.
 *
 * tests/fixtures/decideTrust.module9-baseline.json was generated by running the PRE-Module-15 decideTrust.js (taken
 * from git HEAD before Module 15 was committed) over every input Module 9's own suite uses. Here the CURRENT
 * decideTrust runs over the same inputs; each serialized result must be string-identical to the baseline — not just
 * trustDecision/primaryReason, but riskScore, riskBand, supportingDetail, decidedAt and thrown error codes/messages.
 */

const { decideTrust } = require('../trust/decideTrust');
const { FIXED_NOW_ISO, buildCases, runCase } = require('./fixtures/decideTrustRegressionCases');
const baseline = require('./fixtures/decideTrust.module9-baseline.json');

const cases = buildCases();

beforeEach(() => {
  jest.useFakeTimers();
  jest.setSystemTime(new Date(FIXED_NOW_ISO));
});

afterEach(() => {
  jest.useRealTimers();
});

test('the baseline covers exactly the current Module 9 input set', () => {
  expect(baseline.fixedNow).toBe(FIXED_NOW_ISO);
  expect(baseline.cases.map((c) => c.label)).toEqual(cases.map((c) => c.label));
  expect(new Set(cases.map((c) => c.label)).size).toBe(cases.length);
});

test.each(cases.map((c) => [c.label]))('%s → byte-identical to the pre-Module-15 output', (label) => {
  const current = runCase(decideTrust, cases.find((c) => c.label === label));
  const { label: _label, ...expected } = baseline.cases.find((c) => c.label === label);

  expect(JSON.stringify(current)).toBe(JSON.stringify(expected)); // exact serialized bytes
  if (expected.output) {
    expect([current.output.trustDecision, current.output.primaryReason]).toEqual([expected.output.trustDecision, expected.output.primaryReason]);
  }
});
